import express from 'express'
import bodyParser from "body-parser"

const app = express()
const PORT = 3000

app.use(express.static("public"))
app.use(bodyParser.urlencoded({extended: true}))

let blogs = [
    {
        id: 1,
        title: "consectetur adipiscing",
        author: "vitae nunc",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo urna molestie at elementum. Eu consequat ac felis donec et odio. Risus nullam eget felis eget nunc lobortis. Nulla pellentesque dignissim enim sit amet. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Nunc vel risus commodo viverra maecenas accumsan lacus. Auctor elit sed vulputate mi sit amet mauris commodo. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Tellus cras adipiscing enim eu turpis. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Amet aliquam id diam maecenas ultricies. Consequat interdum varius sit amet. At consectetur lorem donec massa sapien faucibus. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Volutpat est velit egestas dui id ornare.\n" +
            "\n" +
            "Ac auctor augue mauris augue neque gravida in fermentum. Neque sodales ut etiam sit amet nisl purus in mollis. Faucibus turpis in eu mi bibendum neque egestas. Sed arcu non odio euismod lacinia at. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus. Morbi leo urna molestie at elementum eu facilisis. Feugiat scelerisque varius morbi enim nunc faucibus. Elit scelerisque mauris pellentesque pulvinar pellentesque. Quam quisque id diam vel quam elementum. Etiam dignissim diam quis enim lobortis. Fringilla phasellus faucibus scelerisque eleifend. Vitae purus faucibus ornare suspendisse. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Sed egestas egestas fringilla phasellus. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Maecenas sed enim ut sem viverra.\n" +
            "\n" +
            "Quam vulputate dignissim suspendisse in est ante in. Blandit libero volutpat sed cras. Purus gravida quis blandit turpis cursus in hac. Tincidunt vitae semper quis lectus nulla. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Purus in mollis nunc sed id semper risus in hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Ornare arcu odio ut sem nulla pharetra diam. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Posuere lorem ipsum dolor sit. In mollis nunc sed id semper risus in hendrerit. Enim tortor at auctor urna. Placerat in egestas erat imperdiet sed. Euismod quis viverra nibh cras. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Vitae nunc sed velit dignissim sodales ut. Purus ut faucibus pulvinar elementum integer. Scelerisque purus semper eget duis. Purus in massa tempor nec. Morbi quis commodo odio aenean sed adipiscing diam donec.\n" +
            "\n" +
            "Lobortis mattis aliquam faucibus purus in massa tempor. Morbi quis commodo odio aenean. Purus non enim praesent elementum facilisis leo vel. Et magnis dis parturient montes nascetur ridiculus. Vel fringilla est ullamcorper eget nulla. Malesuada proin libero nunc consequat interdum varius sit. Arcu cursus euismod quis viverra nibh cras. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida neque convallis a cras semper auctor neque vitae. A lacus vestibulum sed arcu non odio euismod lacinia. Phasellus vestibulum lorem sed risus ultricies tristique. Fermentum iaculis eu non diam phasellus. Vestibulum lectus mauris ultrices eros in. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Neque egestas congue quisque egestas diam in arcu. Lorem sed risus ultricies tristique nulla aliquet enim. Mauris ultrices eros in cursus turpis massa tincidunt. Aliquam purus sit amet luctus.\n" +
            "\n" +
            "Tristique senectus et netus et malesuada fames ac. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Pellentesque sit amet porttitor eget dolor morbi non. Vestibulum morbi blandit cursus risus at ultrices. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Imperdiet proin fermentum leo vel orci porta non pulvinar. In dictum non consectetur a erat. Enim sit amet venenatis urna cursus eget. Sem viverra aliquet eget sit amet. Nunc congue nisi vitae suscipit.",
        date: "2022-01-15",
        lastUpdated: "2024-01-10"
    },
    {
        id: 2,
        title: "facilisi nullam",
        author: "nec sagittis",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique senectus et netus et malesuada fames. Ut enim blandit volutpat maecenas. Suscipit tellus mauris a diam maecenas sed enim ut. Sagittis purus sit amet volutpat consequat. Auctor eu augue ut lectus arcu bibendum at varius vel. Tellus molestie nunc non blandit. Rhoncus dolor purus non enim praesent. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Enim eu turpis egestas pretium aenean pharetra magna.\n" +
            "\n" +
            "Eget felis eget nunc lobortis mattis. Et malesuada fames ac turpis. Consectetur libero id faucibus nisl tincidunt eget nullam non. Consequat semper viverra nam libero justo laoreet sit amet cursus. Dictum varius duis at consectetur. Posuere urna nec tincidunt praesent semper feugiat nibh. Massa massa ultricies mi quis hendrerit dolor magna. Porttitor lacus luctus accumsan tortor posuere ac ut. Duis at tellus at urna condimentum mattis. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Adipiscing enim eu turpis egestas. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl.\n" +
            "\n" +
            "Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Ultrices neque ornare aenean euismod. Platea dictumst vestibulum rhoncus est pellentesque elit. Tempor orci eu lobortis elementum nibh tellus molestie. Proin libero nunc consequat interdum. Nisi porta lorem mollis aliquam ut porttitor leo. Ipsum a arcu cursus vitae. Orci a scelerisque purus semper eget. Duis ut diam quam nulla porttitor massa id neque. Nisl vel pretium lectus quam. Elementum integer enim neque volutpat ac tincidunt vitae. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Ut lectus arcu bibendum at varius vel pharetra. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Tortor vitae purus faucibus ornare suspendisse sed nisi.\n" +
            "\n" +
            "Turpis egestas maecenas pharetra convallis posuere. Nec feugiat in fermentum posuere urna nec. Ac tortor dignissim convallis aenean et. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Felis eget velit aliquet sagittis id consectetur purus ut. Diam in arcu cursus euismod. Pellentesque habitant morbi tristique senectus et. Sit amet dictum sit amet justo donec enim diam vulputate. Massa id neque aliquam vestibulum morbi blandit. Amet risus nullam eget felis eget. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Est sit amet facilisis magna etiam tempor orci eu. At consectetur lorem donec massa sapien faucibus. Pellentesque nec nam aliquam sem et tortor consequat id. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper.\n" +
            "\n" +
            "Velit egestas dui id ornare. Faucibus et molestie ac feugiat sed lectus. Sit amet aliquam id diam maecenas. Integer feugiat scelerisque varius morbi. Tempus imperdiet nulla malesuada pellentesque elit. Mauris a diam maecenas sed enim ut. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Pulvinar pellentesque habitant morbi tristique senectus. Leo duis ut diam quam nulla porttitor massa id neque. Non nisi est sit amet facilisis magna etiam tempor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Ipsum consequat nisl vel pretium lectus quam id. Sed pulvinar proin gravida hendrerit lectus a. Sed pulvinar proin gravida hendrerit lectus a. Aliquam etiam erat velit scelerisque in. Semper eget duis at tellus at urna. Adipiscing enim eu turpis egestas pretium aenean pharetra. Vel elit scelerisque mauris pellentesque. Lorem ipsum dolor sit amet.",
        date: "2023-08-05",
        lastUpdated: "2023-12-05"
    },
    {
        id: 3,
        title: "mauris pellentesque",
        author: "diam volutpat",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada fames ac turpis egestas sed tempus urna et. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Nunc sed id semper risus in hendrerit gravida. Amet mattis vulputate enim nulla aliquet porttitor lacus. In iaculis nunc sed augue. Facilisis mauris sit amet massa vitae tortor condimentum. Habitant morbi tristique senectus et netus et malesuada fames. Aliquet nibh praesent tristique magna sit. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Mi tempus imperdiet nulla malesuada. Nulla facilisi cras fermentum odio eu feugiat pretium. Eu turpis egestas pretium aenean pharetra magna. Felis donec et odio pellentesque diam. Ipsum suspendisse ultrices gravida dictum fusce ut. Id semper risus in hendrerit gravida rutrum quisque. Ipsum a arcu cursus vitae congue mauris. Tellus mauris a diam maecenas.\n" +
            "\n" +
            "Platea dictumst vestibulum rhoncus est pellentesque elit. Gravida rutrum quisque non tellus orci ac auctor. Egestas pretium aenean pharetra magna ac. Penatibus et magnis dis parturient. Egestas purus viverra accumsan in nisl. Orci phasellus egestas tellus rutrum. Magna sit amet purus gravida quis blandit turpis cursus. Sed odio morbi quis commodo odio aenean sed adipiscing. Felis eget nunc lobortis mattis aliquam faucibus. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Risus quis varius quam quisque id. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. In fermentum posuere urna nec tincidunt praesent semper feugiat.\n" +
            "\n" +
            "Eget egestas purus viverra accumsan. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Fermentum dui faucibus in ornare quam viverra. At lectus urna duis convallis convallis tellus. In fermentum et sollicitudin ac orci. Eget magna fermentum iaculis eu non diam phasellus. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Enim nunc faucibus a pellentesque sit amet. Gravida arcu ac tortor dignissim convallis aenean. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Bibendum enim facilisis gravida neque convallis. Suscipit tellus mauris a diam maecenas.",
        date: "2023-12-16",
        lastUpdated: "2023-06-16"
    },
    {
        id: 4,
        title: "et malesuada",
        author: "orci dapibus",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec ultrices tincidunt arcu non sodales. Sagittis purus sit amet volutpat consequat mauris nunc congue. Erat velit scelerisque in dictum non consectetur a erat nam. Etiam non quam lacus suspendisse faucibus interdum posuere. Turpis egestas pretium aenean pharetra magna ac placerat. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Gravida dictum fusce ut placerat orci nulla. Eget nullam non nisi est sit. Pharetra diam sit amet nisl. Auctor elit sed vulputate mi sit. Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Enim facilisis gravida neque convallis a cras semper auctor neque. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam.\n" +
            "\n" +
            "Faucibus pulvinar elementum integer enim neque volutpat ac. Pretium lectus quam id leo in vitae turpis massa. Facilisi morbi tempus iaculis urna id volutpat lacus. Vitae ultricies leo integer malesuada nunc vel risus commodo. Sed vulputate mi sit amet mauris commodo. Magna etiam tempor orci eu lobortis elementum. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Velit euismod in pellentesque massa placerat duis ultricies lacus. At quis risus sed vulputate odio. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. In eu mi bibendum neque egestas. Elit duis tristique sollicitudin nibh sit. Mi proin sed libero enim sed faucibus turpis in. Vivamus arcu felis bibendum ut tristique.\n" +
            "\n" +
            "Pharetra convallis posuere morbi leo urna molestie at elementum eu. Sit amet consectetur adipiscing elit duis. Montes nascetur ridiculus mus mauris vitae ultricies leo. Quis varius quam quisque id diam vel. Et ligula ullamcorper malesuada proin libero. Volutpat lacus laoreet non curabitur. Mauris commodo quis imperdiet massa. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Massa id neque aliquam vestibulum morbi blandit cursus risus. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. In hac habitasse platea dictumst. Nisl vel pretium lectus quam. Nulla aliquet enim tortor at auctor. Nulla at volutpat diam ut venenatis tellus in metus. Nulla aliquet enim tortor at auctor urna. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Mauris commodo quis imperdiet massa. Velit scelerisque in dictum non consectetur a erat. Velit egestas dui id ornare arcu odio ut sem nulla. Lacus viverra vitae congue eu.\n" +
            "\n" +
            "Porttitor eget dolor morbi non. Venenatis urna cursus eget nunc scelerisque viverra mauris. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Sed euismod nisi porta lorem mollis aliquam ut. A arcu cursus vitae congue. Nulla porttitor massa id neque aliquam vestibulum morbi. Convallis aenean et tortor at. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Etiam tempor orci eu lobortis elementum. Nisi est sit amet facilisis magna etiam tempor orci eu.\n" +
            "\n" +
            "Pulvinar pellentesque habitant morbi tristique senectus et. Dictum non consectetur a erat nam at. Ac tortor dignissim convallis aenean et tortor at risus viverra. Ultricies tristique nulla aliquet enim tortor at auctor. Feugiat in ante metus dictum at tempor commodo. In metus vulputate eu scelerisque felis. Nisi porta lorem mollis aliquam ut. Felis eget nunc lobortis mattis aliquam faucibus purus. Consequat semper viverra nam libero. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. In eu mi bibendum neque egestas congue quisque egestas. Vel pretium lectus quam id leo. Eget aliquet nibh praesent tristique magna. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Placerat in egestas erat imperdiet sed euismod nisi porta. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Molestie nunc non blandit massa enim nec dui nunc. Volutpat consequat mauris nunc congue nisi.\n" +
            "\n" +
            "Risus quis varius quam quisque id diam vel quam. Ut tellus elementum sagittis vitae et leo duis ut. Cursus vitae congue mauris rhoncus aenean vel elit. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Rhoncus urna neque viverra justo nec ultrices dui sapien. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Lobortis scelerisque fermentum dui faucibus. Bibendum enim facilisis gravida neque convallis a. Id cursus metus aliquam eleifend. Sit amet nisl suscipit adipiscing. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Ac auctor augue mauris augue neque gravida. Posuere lorem ipsum dolor sit. Ultrices dui sapien eget mi proin. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Iaculis eu non diam phasellus vestibulum. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra.\n" +
            "\n" +
            "Ut diam quam nulla porttitor massa id neque aliquam. Dolor purus non enim praesent elementum. Ac turpis egestas integer eget aliquet nibh. Eu feugiat pretium nibh ipsum. Id aliquet lectus proin nibh nisl condimentum id venenatis. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. In nibh mauris cursus mattis molestie a iaculis. Adipiscing enim eu turpis egestas pretium aenean. Eget egestas purus viverra accumsan in. In pellentesque massa placerat duis ultricies.\n" +
            "\n" +
            "Cras ornare arcu dui vivamus. Non sodales neque sodales ut etiam sit amet. Tempus quam pellentesque nec nam aliquam sem. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Sit amet porttitor eget dolor morbi non arcu risus quis. Quis commodo odio aenean sed. Eget gravida cum sociis natoque penatibus et. Porttitor eget dolor morbi non arcu risus quis. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Lectus arcu bibendum at varius. At erat pellentesque adipiscing commodo elit at. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Placerat in egestas erat imperdiet sed euismod nisi porta. Sagittis purus sit amet volutpat consequat. Diam maecenas ultricies mi eget mauris pharetra et. Orci a scelerisque purus semper.\n" +
            "\n" +
            "Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Dolor purus non enim praesent elementum facilisis. Congue eu consequat ac felis donec. Congue mauris rhoncus aenean vel elit scelerisque mauris. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Tortor posuere ac ut consequat semper. Pellentesque massa placerat duis ultricies lacus sed. Parturient montes nascetur ridiculus mus mauris vitae. Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Sapien nec sagittis aliquam malesuada bibendum. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. At in tellus integer feugiat scelerisque varius morbi enim. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Ultrices gravida dictum fusce ut placerat orci.\n" +
            "\n" +
            "Elementum nibh tellus molestie nunc non blandit massa enim nec. Consequat semper viverra nam libero. Urna molestie at elementum eu facilisis sed. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Ultrices dui sapien eget mi proin sed. Volutpat odio facilisis mauris sit amet. In nulla posuere sollicitudin aliquam ultrices sagittis. Imperdiet dui accumsan sit amet. Donec ultrices tincidunt arcu non sodales neque sodales. Pellentesque nec nam aliquam sem et. Cras semper auctor neque vitae. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Mauris a diam maecenas sed. Id leo in vitae turpis massa sed elementum. Sem integer vitae justo eget. Ornare arcu dui vivamus arcu felis. Et leo duis ut diam quam nulla porttitor. Ornare arcu dui vivamus arcu felis bibendum ut tristique.",
        date: "2003-10-14",
        lastUpdated: "2003-10-14"
    },
    {
        id: 5,
        title: "ac turpis egestas maecenas",
        author: "odio tempor",
        content: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
        date: "2023-08-21",
        lastUpdated: "2023-08-21"
    },
    {
        id: 6,
        title: "consectetur adipiscing",
        author: "vitae nunc",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2011-01-08",
        lastUpdated: "2011-01-08"
    },
    {
        id: 7,
        title: "facilisi nullam",
        author: "nec sagittis",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2020-03-15",
        lastUpdated: "2020-03-15"
    },
    {
        id: 8,
        title: "mauris pellentesque",
        author: "diam volutpat",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2018-03-25",
        lastUpdated: "2018-03-25"
    },
    {
        id: 9,
        title: "et malesuada",
        author: "orci dapibus",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2010-09-14",
        lastUpdated: "2010-09-14"
    },
    {
        id: 10,
        title: "ac turpis egestas maecenas",
        author: "odio tempor",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2011-01-08",
        lastUpdated: "2011-01-08"
    },
    {
        id: 11,
        title: "consectetur adipiscing",
        author: "vitae nunc",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2023-08-21",
        lastUpdated: "2023-08-21"
    },
    {
        id: 12,
        title: "facilisi nullam",
        author: "nec sagittis",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2020-03-15",
        lastUpdated: "2020-03-15"
    },
    {
        id: 13,
        title: "mauris pellentesque",
        author: "diam volutpat",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2000-12-29",
        lastUpdated: "2000-12-29"
    },
    {
        id: 14,
        title: "et malesuada",
        author: "orci dapibus",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2023-08-21",
        lastUpdated: "2023-08-21"
    },
    {
        id: 15,
        title: "ac turpis egestas maecenas",
        author: "odio tempor",
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eu sem integer vitae justo eget magna. Diam in arcu cursus euismod quis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat vivamus at augue eget arcu dictum varius duis. Eu ultrices vitae auctor eu augue. Purus gravida quis blandit turpis cursus in hac habitasse platea. Facilisis volutpat est velit egestas dui id. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque viverra mauris in aliquam sem fringilla ut. A arcu cursus vitae congue. Viverra vitae congue eu consequat ac felis donec et. Purus in massa tempor nec feugiat nisl.\n" +
            "\n" +
            "Volutpat est velit egestas dui id. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Dui faucibus in ornare quam. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Elementum integer enim neque volutpat ac tincidunt vitae. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Massa tincidunt nunc pulvinar sapien et. Amet massa vitae tortor condimentum lacinia quis. A iaculis at erat pellentesque. Nisi quis eleifend quam adipiscing vitae proin. Dignissim enim sit amet venenatis urna cursus. Lorem mollis aliquam ut porttitor leo a. Interdum varius sit amet mattis vulputate. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Dui vivamus arcu felis bibendum ut tristique et. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius.\n" +
            "\n" +
            "Pellentesque dignissim enim sit amet venenatis urna cursus eget. Lacinia quis vel eros donec ac odio tempor. Leo vel orci porta non. Sed turpis tincidunt id aliquet risus feugiat in. Cursus vitae congue mauris rhoncus aenean vel. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Amet est placerat in egestas erat imperdiet sed. Netus et malesuada fames ac turpis egestas integer. Aliquam purus sit amet luctus. Id porta nibh venenatis cras sed felis eget velit aliquet. Vulputate mi sit amet mauris commodo quis imperdiet massa. Bibendum ut tristique et egestas quis. Euismod in pellentesque massa placerat duis ultricies lacus. Auctor eu augue ut lectus. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Iaculis urna id volutpat lacus laoreet non. Ullamcorper morbi tincidunt ornare massa. Feugiat vivamus at augue eget arcu dictum varius.\n" +
            "\n" +
            "Suspendisse sed nisi lacus sed viverra tellus in. Blandit turpis cursus in hac. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Orci eu lobortis elementum nibh tellus molestie. Egestas tellus rutrum tellus pellentesque. Pretium vulputate sapien nec sagittis aliquam. Consectetur purus ut faucibus pulvinar elementum. Morbi tincidunt ornare massa eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Elementum sagittis vitae et leo duis. Libero nunc consequat interdum varius sit amet mattis vulputate. Vestibulum lorem sed risus ultricies tristique nulla. Tortor pretium viverra suspendisse potenti nullam. Consequat semper viverra nam libero justo laoreet sit amet cursus. At augue eget arcu dictum varius duis. Fames ac turpis egestas integer eget. Ullamcorper sit amet risus nullam eget felis. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n" +
            "\n" +
            "Tempus iaculis urna id volutpat lacus laoreet non. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna et pharetra pharetra massa massa ultricies mi quis. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Volutpat ac tincidunt vitae semper quis. Non arcu risus quis varius quam quisque id. Odio aenean sed adipiscing diam. Iaculis nunc sed augue lacus viverra vitae. Adipiscing elit duis tristique sollicitudin nibh sit. Arcu vitae elementum curabitur vitae nunc sed. Duis tristique sollicitudin nibh sit amet commodo.",
        date: "2000-12-29",
        lastUpdated: "2000-12-29"
    }
]

app.get('/', (req, res) => {
    res.render("index.ejs")
})

app.get('/blogs', (req, res) => {
    res.render("blog_list.ejs", {blogs: blogs})
})

app.get('/blogs/:id', (req, res) => {
    const id = parseInt(req.params.id)
    let blog = blogs.find((b) => b.id === id)
    let updatedContent = blog.content.replace(/\n/g, '<br>')
    blog['content'] = updatedContent
    res.render('blog.ejs', {blog: blog})
})

app.get('/create', (req, res) => {
    res.render('create.ejs')
})

app.post('/create', (req, res) => {
    let id = blogs[blogs.length - 1].id + 1
    let d = new Date()
    let year = d.getFullYear()
    let month = d.toLocaleString('default', {month: 'long'})
    const blog = {
        id: id,
        title: req.body.title,
        author: req.body.title,
        content: req.body.content,
        date: month + ', ' + year,
        lastUpdated: month + ', ' + year
    }
    blogs.push(blog)
    res.redirect(`/blogs/${id}`)
})

app.get('/edit/:id', (req, res) => {
    const id = parseInt(req.params.id)
    const blog = blogs.find((b) => b.id === id)

    res.render('edit.ejs', {blog: blog})
})

app.post('/edit/:id', (req, res) => {
    const id = parseInt(req.params.id)
    const d = new Date()
    console.log(req.body.content)
    blogs = blogs.map(blog => {
        if (blog.id === id) {
            return {
                ...blog,
                title: req.body.title,
                author: req.body.author,
                content: req.body.content,
                lastUpdated: d.toLocaleString('default', {month: 'long'}) + ', ' + d.getFullYear()
            }
        }
        return blog
    })
    res.redirect(`/blogs/${id}`)

})

app.get('/delete/:id', (req, res) => {
    const id = parseInt(req.params.id)
    blogs = blogs.filter((blog)=> blog.id!==id)
    res.redirect('/blogs')
})

app.listen(PORT, () => {
    console.log(`listening on ${PORT}`)
})




